runtime: python39

# Set timeout when starting the server
readiness_check:
  app_start_timeout_sec: 3600

# Set timezone
env_variables:
  TZ: 'Asia/Bangkok'

# Set timeout and bind address when running the server
entrypoint: gunicorn -t 3600 -b :$PORT main:app

service: default