runtime: python39

# Set timeout when starting the server
readiness_check:
  app_start_timeout_sec: 600

# Set my timezone
env_variables:
  TZ: 'Asia/Bangkok'

# Set timeout when running server
entrypoint: gunicorn -t 600 -b :$PORT main:app